class_name ArtSprites
extends RefCounted
## Every pixel sprite in the game, drawn as text. One character per pixel, keyed
## by `ArtPalette.COLORS`; `.` is transparent. Compiled to PNG by ArtGenerator.
##
## Read these like pictures — that is the whole point of the format. Squint and
## the ranger's hood is visibly a hood.
##
## Three rules hold the set together, and breaking any of them will make a new
## sprite look wrong beside the others even when it looks fine on its own:
##
##  1. **One skeleton.** Every upright humanoid uses the same proportions —
##     head rows 4-19, torso 20-31, legs 32-47, body between columns 7 and 24.
##     A roster reads as a roster because the silhouettes are siblings; class is
##     carried by headgear, colour and the weapon, which is also how a player
##     tells them apart at this size.
##  2. **Feet on the last row.** The Sprite3D anchors in player.tscn/enemy.tscn
##     put the bottom of a 48 px texture exactly on the ground plane, so a
##     figure floats or sinks if it does not end on row 47.
##  3. **Key light top-left.** Light steps up-left, dark steps down-right.
##
## Sizes are declared by ArtGenerator, not here: CHARACTERS are 32x48 and SMALL
## are 32x32, and a row of the wrong length is a hard error rather than a shrug.

## Upright figures — the three classes and the three enemies. 32x48.
const CHARACTERS := {

# --- Ranger: green hood, leather jerkin, longbow held at the right ----------
"player_ranger": [
	"................................",
	"................................",
	"................................",
	"................................",
	"...........0000000000...........",
	"..........0hggggggggh0..........",
	".........0hgggggggggGh0.........",
	".........0hggggggggGGGh0........",
	".........0hgggggggGGGGh0........",
	".........0hgg0ssssss0GGh0.......",
	".........0hg0ssssssss0Gh0.......",
	".........0hg0ssssssss0Gh0.......",
	".........0hg0s00ss00s0Gh0.......",
	".........0hg0ssssssss0Gh0.......",
	".........0hg0sSskksSs0Gh0.......",
	".........0hgg0SSSSSS0GGh0..0....",
	".........0hggg0SSSS0GGGh0.nw....",
	"..........0hgggg00ggGGh0..n.w...",
	"..........0hggggggggGGh0..n.w...",
	"...........0hggggggGh0....n..w..",
	"........00hggggggggGh00...n..w..",
	".......0GGhgggggggggghGG0.n..w..",
	".......0GGhwwxxxxxxwwhGG0.n..w..",
	".......0GGhwwWxxxxWwwhGG0.n..w..",
	".......0GGhwwWWxxWWwwhGG0sssSw..",
	".......0GGhwwWWWWWWWxhGG0.ssSw..",
	".......0GGhwWWWWWWWxxhGG0.n..w..",
	"........0GhwWWWWWWxxxhG0..n..w..",
	"........0ShgwxxxxxxwghS0..n.w...",
	"........0SshxxxxxxxxhsS0..n.w...",
	"........00s0hGGGGGGh0s00..nw....",
	".........000.0GGGGGG0.000..0....",
	"............0GGGGGGG0...........",
	"............0GG000GG0...........",
	"............0GG0.0GG0...........",
	"............0GG0.0GG0...........",
	"............0WW0.0WW0...........",
	"............0WW0.0WW0...........",
	"............0Ww0.0Ww0...........",
	"............0Ww0.0Ww0...........",
	"............0Ww0.0Ww0...........",
	"............0xx0.0xx0...........",
	"............0xx0.0xx0...........",
	"............0xx0.0xx0...........",
	"...........0xxx0.0xxx0..........",
	"...........0xxx0.0xxx0..........",
	"..........0xxxx0.0xxxx0.........",
	"..........000000.000000.........",
],

# --- Paladin: plate, gold trim and crest, warhammer shouldered at the right -
"player_paladin": [
	"..............yy................",
	".............yYYy...............",
	"............yYYuYy..............",
	"...........0yYuuYy0.............",
	"...........0000000000...........",
	"..........0dlllllllld0..........",
	".........0dlllllllllLd0.........",
	".........0dllllllllLLLd0........",
	".........0dlllllllLLLLd0........",
	".........0dll0ssssss0LLd0.......",
	".........0dl0ssssssss0Ld0.00000.",
	".........0dl0ssssssss0Ld00lLLd0.",
	".........0dl0s00ss00s0Ld00lLLd0.",
	".........0dl0ssssssss0Ld00lLLd0.",
	".........0dl0sSskksSs0Ld00LLddd0",
	".........0dll0SSSSSS0LLd00LLddd0",
	".........0dlll0SSSS0LLLd0.00000.",
	"..........0dllll00llLLd0....W...",
	"..........0dllllllllLLd0....W...",
	"...........0dllllllLd0......W...",
	"........00dllllllllLd00.....W...",
	".......0LLdlllllllllldLL0...W...",
	".......0LLdlyyyyyyyyldLL0...W...",
	".......0LLdllLLLLLLlldLL0...W...",
	".......0LLdllLLLLLLdddLL0...W...",
	".......0LLdlLLLLLLLdddLL0...W...",
	".......0LLdlLLLLLLddddLL0...W...",
	"........0LdlLLLLLdddddL0....W...",
	"........0SdyYYYYYYYYydS0.sssW...",
	"........0SsddddddddddsS0.sssW...",
	"........00s0dLLLLLLd0s00....W...",
	".........000.0LLLLLL0.000...W...",
	"............0LLLLLLL0...........",
	"............0LL000LL0...........",
	"............0LL0.0LL0...........",
	"............0LL0.0LL0...........",
	"............0Ll0.0Ll0...........",
	"............0Ll0.0Ll0...........",
	"............0Ll0.0Ll0...........",
	"............0dL0.0dL0...........",
	"............0dL0.0dL0...........",
	"............0dd0.0dd0...........",
	"............0dd0.0dd0...........",
	"............0dd0.0dd0...........",
	"...........0ddd0.0ddd0..........",
	"...........0ddd0.0ddd0..........",
	"..........0dddd0.0dddd0.........",
	"..........000000.000000.........",
],

# --- Mage: pointed hat, robe skirt instead of legs, orb-topped staff --------
# The robe is the one deliberate break from the shared skeleton: a flaring hem
# gives the Mage a silhouette nobody else has, which at 32 px does more work
# than any amount of detail on the robe itself.
"player_mage": [
	"...............0................",
	"..............0V0...............",
	"..............0V0...............",
	".............0VVm0.........00...",
	".............0VVm0.......0cc0...",
	"............0vVVmm0......0c#cc0.",
	"...........0vVVVmmm0.....0cccc0.",
	"..........0vVVVVmmmm0.....0cc0..",
	".......000vvVVVVVmmmmm000..00...",
	"......0vvvvvvVVVVVVmmmmmm0.W....",
	"......00000000000000000000.W....",
	"..........0k0ssssss0k0.....W....",
	".........0kk0ssssss0kk0....W....",
	".........0k0sc0ss0cs0k0....W....",
	".........0k0ssssssss0k0....W....",
	".........0kk0ssssss0kk0....W....",
	"..........0k0SSSS0k0.......W....",
	"..........0BBBBBBBB0.......W....",
	"...........0BBBBBB0........W....",
	"........000vVVVVVVv000.....W....",
	".......0VV0vVVVVVVv0VV0....W....",
	".......0Vm0vVVVVVVv0mV0....W....",
	".......0Vm0vVVccVVv0mV0....W....",
	".......0Vm0vVVccVVv0mV0....W....",
	".......0Vm0vVVVVVVv0mV0....W....",
	".......0Sm0vVVVVVVv0mS0....W....",
	".......0Ss0vVVVVVVv0sS0....W....",
	"........00.0vVVVVVv0.00....W....",
	"...........0vVVVVVv0.......W....",
	"..........0vVVVVVVv0.......W....",
	"..........0vVVVVVVv0.......W....",
	".........0vVVVVVVVVv0......W....",
	".........0vVVVVVVVVv0......W....",
	"........0vVVVVmmVVVVv0.....W....",
	"........0vVVVVmmVVVVv0.....W....",
	".......0vVVVVVmmVVVVVv0....W....",
	".......0vVVVVVmmVVVVVv0....W....",
	"......0vVVVVVVmmVVVVVVv0...W....",
	"......0vVVVVVVmmVVVVVVv0...W....",
	"......0VVVVVVVmmVVVVVVV0...W....",
	".....0vVVVVVVVmmVVVVVVVv0..W....",
	".....0VVVVVVVVmmVVVVVVVV0.......",
	".....0mVVVVVVVmmVVVVVVVm0.......",
	"....0mVVVVVVVVmmVVVVVVVVm0......",
	"....0mmVVVVVVVmmVVVVVVVmm0......",
	"....0mmmVVVVVVmmVVVVVVmmm0......",
	"....0mmmmmmmmmmmmmmmmmmmm0......",
	"....0000000000000000000000......",
],

# --- Shambler: rotting flesh, tattered wrappings, hunched and neckless ------
"shambler": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"...........0000000000...........",
	"..........0eRRRRRRRRe0..........",
	".........0eRRRRRRRRRRe0.........",
	".........0eRrrrrrrrRRe0.........",
	".........0eRr00rr00rRe0.........",
	".........0eRrrrrrrrrRe0.........",
	".........0eRr0rrrr0rRe0.........",
	".........0eRrr0000rrRe0.........",
	"..........0eRrrrrrrRe0..........",
	"...........0eRrrrrRe0...........",
	"............0eRRRe0.............",
	"..........000eRRRe000...........",
	".........0BBeRRRRRReBB0.........",
	".........0BneRrrrrRenB0.........",
	".........0nBeRe00eReBn0.........",
	".........0BneRrrrrRenB0.........",
	".........0nBeRe00eReBn0.........",
	".........0RneRrrrrRenR0.........",
	".........0RreRe00eRerR0.........",
	".........0rreReeeeRerr0.........",
	".........0ereeeeeeeere0.........",
	".........0ereeRRRReere0.........",
	"..........00.0RRRR0.00..........",
	".............0RRRR0.............",
	"............0RRRRRR0............",
	"...........0BBBBBBBB0...........",
	"..........0BnnBBBBnnB0..........",
	"..........0Bnn0000nnB0..........",
	"............0RR00RR0............",
	"............0RR0.0RR0...........",
	"............0Rr0.0Rr0...........",
	"............0Rr0.0Rr0...........",
	"............0Rr0.0Rr0...........",
	"............0eR0.0eR0...........",
	"............0eR0.0eR0...........",
	"............0eR0.0eR0...........",
	"............0ee0.0ee0...........",
	"............0ee0.0ee0...........",
	"...........0eRR0.0eRR0..........",
	"...........0eRR0.0eRR0..........",
	"...........0eRRR0.0eRRR0........",
	"...........000000.000000........",
],

# --- Wretch: small and low, so it reads as lesser before you read its colour -
"wretch": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	".............000000.............",
	"............0eRRRRe0............",
	"...........0eRrrrrRe0...........",
	"...........0Rr00rr00R0..........",
	"...........0Rrrrrrrr0...........",
	"...........0Rr0rrr0r0...........",
	"............0RrrrrR0............",
	"............00RRRR00............",
	"..........00eRrrrrRe00..........",
	".........0RreRe00eRerR0.........",
	".........0RreRrrrrRerR0.........",
	".........0rreRe00eRerr0.........",
	".........0ereeeeeeeere0.........",
	".........0e0.0RRRR0.0e0.........",
	"..........0..0RRRR0..0..........",
	".............0RRRR0.............",
	"............0RRRRRR0............",
	"............0RR00RR0............",
	"............0Rr0.0Rr0...........",
	"............0Rr0.0Rr0...........",
	"............0Rr0.0Rr0...........",
	"............0eR0.0eR0...........",
	"............0eR0.0eR0...........",
	"............0eR0.0eR0...........",
	"............0ee0.0ee0...........",
	"............0ee0.0ee0...........",
	"............0ee0.0ee0...........",
	"...........0eeR0.0eeR0..........",
	"...........0eeR0.0eeR0..........",
	"...........0eeR0.0eeR0..........",
	"..........0eRRR0.0eRRR0.........",
	"..........000000.000000.........",
],

# --- Marauder: living bandit. Red hood and steel axe, so a player can tell at
# --- a glance that the camp garrison is not another shambling corpse. --------
"marauder": [
	"................................",
	"................................",
	"................................",
	"................................",
	"...........0000000000...........",
	"..........0qffffffffq0..........",
	".........0qfffffffffFq0.........",
	".........0qffffffffFFFq0........",
	".........0qfffffffFFFFq0..W.000.",
	".........0qff0ssssss0FFq0.W0llL0",
	".........0qf0ssssssss0Fq0.W0lLL0",
	".........0qf0ssssssss0Fq0.W0lLL0",
	".........0qf0s00ss00s0Fq0.W0lLL0",
	".........0qf0ssssssss0Fq0.W0LLd0",
	".........0qf0sSskksSs0Fq0.W0LLd0",
	".........0qff0SSSSSS0FFq0.W0LLd0",
	".........0qfff0SSSS0FFFq0.W.0Ld0",
	"..........0qffff00ffFFq0..W.00..",
	"..........0qffffffffFFq0..W.....",
	"...........0qffffffFq0....W.....",
	"........00qffffffffFq00...W.....",
	".......0WWxwwwwwwwwwwxWW0.W.....",
	".......0WWxwwxxxxxxwwxWW0.W.....",
	".......0WWxwwWxxxxWwwxWW0.W.....",
	".......0WWxwwWWxxWWwwxWW0.W.....",
	".......0WWxwWWWWWWWxxxWW0.W.....",
	".......0WWxwWWWWWWxxxxWW0.W.....",
	"........0WxwWWWWWxxxxxW0..W.....",
	"........0SxqqqqqqqqqqxS0.sW.....",
	"........0SsxxxxxxxxxxsS0.sW.....",
	"........00s0xWWWWWWx0s00..W.....",
	".........000.0WWWWWW0.000.W.....",
	"............0WWWWWWW0...........",
	"............0WW000WW0...........",
	"............0WW0.0WW0...........",
	"............0WW0.0WW0...........",
	"............0Ww0.0Ww0...........",
	"............0Ww0.0Ww0...........",
	"............0Ww0.0Ww0...........",
	"............0xW0.0xW0...........",
	"............0xW0.0xW0...........",
	"............0xx0.0xx0...........",
	"............0xx0.0xx0...........",
	"............0xx0.0xx0...........",
	"...........0xxx0.0xxx0..........",
	"...........0xxx0.0xxx0..........",
	"..........0xxxx0.0xxxx0.........",
	"..........000000.000000.........",
],
}


## Ground decals, world billboards and shot sprites. 32x32.
const SMALL := {

# --- The character drop shadow. Not a drawing: a soft ellipse in three alpha
# --- steps, stretched onto a 0.75 x 0.32 plane under every figure. ----------
"shadow": [
	"................................",
	"................................",
	"................................",
	"................................",
	"..........,,,,,,,,,,,,..........",
	".......,,,,,,,,,,,,,,,,,,.......",
	".....,,,,,,;;;;;;;;;;,,,,,,.....",
	"....,,,,;;;;;;;;;;;;;;;;,,,,....",
	"...,,,;;;;;;;;;;;;;;;;;;;;,,,...",
	"..,,,;;;;;;;::::::::;;;;;;;,,,..",
	"..,,;;;;;;::::::::::::;;;;;;,,..",
	".,,;;;;;::::::::::::::::;;;;;,,.",
	".,,;;;;::::::::::::::::::;;;;,,.",
	".,;;;;::::::::::::::::::::;;;;,.",
	".,;;;;::::::::::::::::::::;;;;,.",
	",,;;;;::::::::::::::::::::;;;;,,",
	",,;;;;::::::::::::::::::::;;;;,,",
	".,;;;;::::::::::::::::::::;;;;,.",
	".,;;;;::::::::::::::::::::;;;;,.",
	".,,;;;;::::::::::::::::::;;;;,,.",
	".,,;;;;;::::::::::::::::;;;;;,,.",
	"..,,;;;;;;::::::::::::;;;;;;,,..",
	"..,,,;;;;;;;::::::::;;;;;;;,,,..",
	"...,,,;;;;;;;;;;;;;;;;;;;;,,,...",
	"....,,,,;;;;;;;;;;;;;;;;,,,,....",
	".....,,,,,,;;;;;;;;;;,,,,,,.....",
	".......,,,,,,,,,,,,,,,,,,.......",
	"..........,,,,,,,,,,,,..........",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Essence wisp. Deliberately near-white at the core: ResourceNode tints it
# --- per material, and a tint can only darken a colour that is already pale.
"essence_wisp": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	".....................c..........",
	"................................",
	"................................",
	"..............0000..............",
	"............00cccc00............",
	"...........0c#ccccCC0...........",
	"..........0c##ccccCCj0..........",
	"..........0c#cccccCCj0..........",
	"..........0ccccccccCj0..........",
	"..........0cCcccccCCj0..........",
	"...........0CCccccCj0...........",
	"............00CCjj00............",
	"..............0000..............",
	"................................",
	"............C...................",
	"................................",
	".................c..............",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Dry grass tuft ---------------------------------------------------------
"grass_tuft": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"..............g.................",
	".........g....g......g..........",
	".........g...g.g....g...........",
	"..........g..g.g...g............",
	"..........G..G.G..G.............",
	"...........G.G.G.G..............",
	"...........G.GGG.G..............",
	"............GGGGG...............",
	"............hGGGh...............",
	"............hhGhh...............",
	".............hhh................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Bones: a skull and a long bone. Reads as "something died here" at a
# --- glance, which is the entire job of a decal. ----------------------------
"bones": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"............bbbbbb..............",
	"...........bBBBBBBb.............",
	"...........b00BB00b.............",
	"...........bBBBBBBb.............",
	"...........bBB00BBb.............",
	"............bBBBBb..............",
	"............b0b0b...............",
	".............nnn................",
	"................................",
	".....bb...................bb....",
	"....bBBb.................bBBb...",
	".....nBBBBBBBBBBBBBBBBBBBBn.....",
	"....bBBBBBBBBBBBBBBBBBBBBBBb....",
	".....nBBBBBBBBBBBBBBBBBBBBn.....",
	"....bBBb.................bBBb...",
	".....bb...................bb....",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Rubble ----------------------------------------------------------------
"rubble": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	".............00000..............",
	"............0lLLL0..............",
	"...........0lLLLLd0.............",
	"...........0LLLLdd0....000......",
	"...........0LLdddd0...0lLL0.....",
	"...........0Ldddd00...0Lddd0....",
	"............zzzzz0....0ddd0.....",
	".............zzz.......zzz......",
	".....000........................",
	"....0lLL0.......................",
	"....0Lddd0......................",
	".....zzzz.......................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Snare trap: a ring of braced wood. Ground decal, so it is drawn as seen
# --- from above rather than in the characters' 3/4 view. --------------------
"snare_trap": [
	"................................",
	"................................",
	"................................",
	"................................",
	"............WWWWWW..............",
	".........WWWwwwwwwWWW...........",
	".......WWww........wwWW.........",
	"......Www............wwW........",
	".....Www..............wwW.......",
	"....Www................wwW......",
	"....Ww..................wW......",
	"...Www..................wwW.....",
	"...Ww....................wW.....",
	"...Ww....................wW.....",
	"..Www....................wwW....",
	"..Ww......................wW....",
	"..Ww......................wW....",
	"..Www....................wwW....",
	"...Ww....................wW.....",
	"...Ww....................wW.....",
	"...Www..................wwW.....",
	"....Ww..................wW......",
	"....Www................wwW......",
	".....Www..............wwW.......",
	"......Www............wwW........",
	".......WWww........wwWW.........",
	".........WWWwwwwwwWWW...........",
	"............WWWWWW..............",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Ember sigil: the snare's ring re-lit. Same geometry on purpose — they are
# --- the same *kind* of thing (a circle on the ground that means "do not stand
# --- here"), and a player who has learned to read one should read the other.
"ember_sigil": [
	"................................",
	"................................",
	"................................",
	"................................",
	"............OOOOOO..............",
	".........OOOooooooOOO...........",
	".......OOoo........ooOO.........",
	"......Ooo............ooO........",
	".....Ooo....pppppp....ooO.......",
	"....Ooo....pOOOOOOp....ooO......",
	"....Oo....pO0oooo0Op....oO......",
	"...Ooo...pO0oo00oo0Op...ooO.....",
	"...Oo....pOoo0oo0ooOp....oO.....",
	"...Oo....pOo0oooo0oOp....oO.....",
	"..Ooo....pOo0o00o0oOp....ooO....",
	"..Oo.....pOo0oooo0oOp.....oO....",
	"..Oo.....pOo0oooo0oOp.....oO....",
	"..Ooo....pOo0o00o0oOp....ooO....",
	"...Oo....pOo0oooo0oOp....oO.....",
	"...Oo....pOoo0oo0ooOp....oO.....",
	"...Ooo...pO0oo00oo0Op...ooO.....",
	"....Oo....pO0oooo0Op....oO......",
	"....Ooo....pOOOOOOp....ooO......",
	".....Ooo....pppppp....ooO.......",
	"......Ooo............ooO........",
	".......OOoo........ooOO.........",
	".........OOOooooooOOO...........",
	"............OOOOOO..............",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Arrow. Drawn pointing right; Projectile flips it for leftward flight. ---
"arrow_shot": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"......................0.........",
	".....b...............0L0........",
	".....bbwwwwwwwwwwwww0lLLL0......",
	".....bbWWWWWWWWWWWWW0lLLL0......",
	".....b...............0L0........",
	"......................0.........",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
],

# --- Arcane bolt: a violet comet with its tail trailing left ----------------
"arcane_bolt": [
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"..................0000..........",
	"...........v....0vVVVV0.........",
	"........vvvvvvv0v#vVVVm0........",
	"......vvVVVVVVv0v#vVVVm0........",
	"......vvVVVVVVv0vvVVVVm0........",
	"........vvvvvvv0vVVVVm0.........",
	"...........v....0mVVm0..........",
	"..................0000..........",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
	"................................",
],
}

## Ground tiles. 32x32, fully opaque, and sampled by ground.gdshader rather than
## drawn on a Sprite3D — the ground is the one surface in the game big enough
## that a repeating tile is the only sane way to texture it.
##
## Two rules are specific to tiles and neither applies to any sprite above:
##
##  1. **They must wrap.** The shader repeats them, so column 31 sits against
##     column 0 and row 31 against row 0. Scattered speckle wraps for free;
##     anything with a shape (a rut, a paving stone) has to be drawn across the
##     seam by hand.
##  2. **Keep the contrast low.** A tile the player sees several thousand times
##     in a frame is texture, not decoration — any feature strong enough to
##     notice on its own becomes a visible grid at a distance. What actually
##     breaks the repeat is the per-cell brightness jitter in the shader, not
##     the drawing.
##
## The first pair is the gradient the ground shader has always painted, now with
## a surface on it: living grass near the tower, dead ground out in the wilds.
## The third is bare trodden ground, used everywhere the world has been walked
## flat — the approach roads and the ring at the village boundary (session 18).
const TILES := {

# --- Village turf: the lit ground inside the glow. Mid green with a light
# --- step for catching blades and the dark step for the gaps between. -------
"ground_village": [
	"GGGGhGGGGgGhGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGghGGGGggGGGgGGGGGGGGGG",
	"GggGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"GGgGGGGGGGGgGGGGGGGGGGGGGGGGGGGG",
	"GGgGGGGGGGgGGGGGgGGgGGGGgGGGGGGG",
	"GGGGGGGGGGGGGGGhGGGgGGGhhhgGGGGG",
	"GGGGGGhGGGGGGGGGGGGGGGGGGgGGGGGG",
	"GGGgGGGgGGGGGGGGGGGGGGgGGGGGGGGG",
	"GGGGGGhhGGGGGGGGGGhhGGGGGGGgGGGG",
	"GGGgGGGGGGGGGGGGGGgGGGGGGGGgGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGGhGGGGGGG",
	"GGGgGGGGGGGGGGGGGGGGGGGhGGGGGhhh",
	"GGgGGGGGGgGGhGGGGGGGGGGGGGGGGGGG",
	"GGgGGGGGGGGGGgGGGGGGGGGGGGGGGGGG",
	"hhGGGGGGGGGGGGGGGGgGGGGGGGGGGGGg",
	"GGGGGGGGGGGGGGGGGgGGGGGGGGGGGGGG",
	"gGGGGGGGGGGGGGGGGGGGhGgGGGGGGGGG",
	"GGggGGGGGGGggGGGhGGGGGGhGGGGGGGG",
	"GGGGGgGGGGGgGGGGGGGgGGGGhGGGGGgG",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGgGG",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"GgGGGGgGGGGGGGGGGGGGGGGGGGGGGGGh",
	"hGGGGGgGhGGGGGGGGGGGGGGGGGGhGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGhhGGGG",
	"GggGGhGGGGGGGGGGGGGGGGGGGGGhGGGG",
	"GGGGGGGGGGhGGGGGGGGGhGGGGGGGhhGG",
	"GGGGGGGGGGGGGGGGGGGGGhGGGGGhhGGG",
	"GggGGGGGGGGGghGGGGGGGGGGgGGGGGGh",
	"GGGGGGGGGGGGgGGGgghGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGhGGhGgGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGgGggGG",
	"GGGGGGGGGgGGGGGGGGGGgGGGGGGGGGGG",
],

# --- Wilds dirt: dry, dead ground beyond the light. Same speckle density as
# --- the turf so the two blend without a visible change of texture. ---------
"ground_wilds": [
	"TTTTTtzTzTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTzTTzTTTTTTTTTTTTTTTTTzTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTtTTTTttTTTTT",
	"TTTTTtTTTTTTTTTTTTzzTTTTTTTTTTTT",
	"TzTTTTzTTtTTTTTTTTTTTTTTTtTTTTTT",
	"ttzTTTTTTTTTTTtTTTTTTTTTTTTTTTtT",
	"TTtttTTTTTttTTTzTTtTTTTTTTtTTTTT",
	"TTTTTTtTTTTTTTzTTTTTTTTTTTTtTTTT",
	"TTTTTTTTTTttTTzTTTzTTTTTTtTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTzTTTTTTTT",
	"TTTTzTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTtTTTTTTTTTTTTTTTTTtTTTTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"zTTTTTTTTTTtTTtTTTzTTzTTTTTTTTTz",
	"TTTTTTTTTTTTTTTTTTTTzTTTTTTTTTTT",
	"TTTTTtTTTTTTTTtTTTTzTTTTTTTTTTTT",
	"TTzTTTTTTTTTTTtTTTTTTTTTTTTTTTTT",
	"TTTTTTTTTTTTzzTtTTTTTTTTTTTzTTTT",
	"TTTTTTTTTTTTTTTzTTTTTTTTTTTzttTT",
	"zTzTtTTTTTTTTTTTtTTTTTTTTTzTTTtT",
	"TTTTtTTTTTzTTTTTTTTTTTTTTTTTTTTz",
	"TTTTTTTTTTzTTTTTTTTTTTTTTtTTTzTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTtTTTzTTT",
	"TTzTTTTTTTTTTTTTTTTTttTTTTTTTzTT",
	"TTTzTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
	"TTTTTTTTtTTTTTTzTTTTTTTTTTTTTTTt",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTTzTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTTTzTTTT",
	"TTTTTTTTTTTTTTTTTTTTTTTTTzTTTTTT",
	"TtTTTTTTTTtTtTTTTTTTTTzzTTzTTTTT",
	"TTtTTTTTTTTTTTTttTTTTTTTTTTTTTTT",
],

# --- Trodden path: bare, scuffed earth, one step LIGHTER than the wilds dirt
# --- so a road reads against both the turf and the dark ground. Ruts run
# --- across the tile and wrap, but only in the dark step: a rut with any real
# --- contrast turns the whole road into a ladder at map scale. --------------
"ground_path": [
	"tttTtttttttzttttttttttttTttttttt",
	"ttttttTttttttttttzttttttttttttnt",
	"ttzttttttttttttttttttTtttttttttt",
	"ttttttttttTttttttttttttttzttttTt",
	"tTttttttttttttzttttttttttttttttt",
	"tttttztttttttttttttTtttttttttttt",
	"ntttttttttttTtttttttttttttzttttt",
	"tttttttttztttttttttttttttttttttt",
	"tttTttttttttttttTtttttztttttttTt",
	"ttttttttttttztttttttttttttttnttt",
	"tzttttTtttttttttttttttTttttttttt",
	"ttttttttttttttttztttttttttttzttt",
	"tttttttttttTtttttttttttttttttttt",
	"ttTtttztttttttttttTttttztttttttt",
	"tttttttttttttttttttttttttttTtttt",
	"tttztttttttnttttttttztttttttttzt",
	"Tttttttttttttttttttttttttttttttt",
	"tttttttTtttttztttttttttTtttttttt",
	"ttttttttttttttttttttttttttttzttt",
	"tzttttttttTtttttttztttttttttttTt",
	"ttttTttttttttttttttttttttttttttt",
	"tttttttttzttttTttttttttttznttttt",
	"tttztttttttttttttttttttttttttttt",
	"tttttttttttttttztttTtttttttttttt",
	"tTtttttztttttttttttttttttttTtttt",
	"tttttttttttttttttttttztttttttttt",
	"ttttztttTtttttttttttttttttttttzt",
	"ttttttttttttttztttttttTttttttttt",
	"tttTtttttttttttttttttttttttttttt",
	"ttttttttztttttttttztttttttttTttt",
	"tttttttttttttTtttttttttttttttttt",
	"tzttTttttttttttttttttttztttttttt",
],
}
